# Generated by Django 5.2.1 on 2025-05-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bombay_Exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='listings',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='stocks',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='listing_status',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='quantity',
        ),
        migrations.AddField(
            model_name='listings',
            name='listing_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Expired', 'Expired')], default='Pending'),
        ),
        migrations.AddField(
            model_name='listings',
            name='listing_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Error', 'Error')], default='Error'),
        ),
        migrations.AddField(
            model_name='listings',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
