# Generated by Django 5.2.1 on 2025-05-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bombay_Exchange', '0002_users_alter_listings_options_alter_stocks_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocks',
            options={},
        ),
    ]
