# Generated by Django 5.2.1 on 2025-05-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bombay_Exchange', '0003_alter_stocks_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='Token',
            field=models.TextField(max_length=120),
        ),
    ]
