# Generated by Django 5.2.1 on 2025-05-11 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bombay_Exchange', '0004_alter_stocks_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='Token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bombay_Exchange.stocks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocks',
            name='Token',
            field=models.TextField(max_length=120, unique=True),
        ),
    ]
