# Generated by Django 5.2.1 on 2025-05-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bombay_Exchange', '0006_trades_delete_users_listings_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='user',
            new_name='User',
        ),
    ]
